{% set version = "3.6.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 44aa7c704c2b7d8fb3d483bbf75af6cb2350d30a63b144279a09b75fead501bf
  patches:
    - 0001-azimuthal-equidistant.patch

build:
  number: 7
  skip: true  # [py<39 or ppc64le]
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    # based on https://github.com/conda-forge/python-feedstock/blob/3732e621ad28b925e402c3c1d8542bac029920ad/recipe/build_base.bat#L28-L30
    - for /f "usebackq delims=" %%i in (`conda list -p %PREFIX% proj --no-show-channel-urls --json ^| findstr "version"`) do set PROJ_VERSION_LINE=%%i  # [win]
    - for /f "tokens=2 delims==/ " %%i IN ('echo %PROJ_VERSION_LINE%') do (set PROJ_VERSION=%%~i)                                                       # [win]
    - echo PROJ_VERSION detected as %PROJ_VERSION%                                                                                                      # [win]
    - export PROJ_VERSION=$(conda list -p $PREFIX proj | grep -v '^#' | tr -s ' ' | cut -f 2 -d ' ')                                                    # [unix]
    - echo "PROJ_VERSION detected as ${PROJ_VERSION}"                                                                                                   # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - export "PROJ_NETWORK=ON"           # [unix]
    - export "PYPROJ_GLOBAL_CONTEXT=ON"  # [unix]
    - set "PROJ_NETWORK=ON"              # [win]
    - set "PYPROJ_GLOBAL_CONTEXT=ON"     # [win]
    - python -m pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_proj
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
    - zklaus
