{% set version = "3.7.2rc0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: dcf8ecd1a83ef7fadeafe635e1e2dd146a20cd31419aa58fdadbff23a9b7f3ce

build:
  number: 0
  skip: true  # [py<311]
  entry_points:
    - pyproj=pyproj.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - proj
    - setuptools
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - export "PROJ_NETWORK=ON"           # [unix]
    - export "PYPROJ_GLOBAL_CONTEXT=ON"  # [unix]
    - set "PROJ_NETWORK=ON"              # [win]
    - set "PYPROJ_GLOBAL_CONTEXT=ON"     # [win]
    # needed for a test_transform_single_point_nad83_to_nad27 to pass on ppc64le
    # see https://github.com/conda-forge/proj.4-feedstock/issues/148
    - projsync --file us_noaa_nadcon5_nad27_nad83_1986_conus.tif  # [ppc64le]
    - python -m pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_proj
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
    - zklaus
