{% set version = "3.4.1rc0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: c1f911cf1952a83e364acc943d787f8e7bf425db71247d7d30d4bff375539d77

build:
  number: 2
  skip: true  # [py<38]
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    - export "PROJ_VERSION={{ proj }}"  # [unix]
    - set "PROJ_VERSION={{ proj }}"     # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    # remove the skipped test in the next pyproj release
    - pytest -v -s -k "not test_get_transform_grid_list__contains"
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
