{% set version = "1.9.5.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  fn: pyproj-{{ version }}.tar.gz
  url: https://github.com/jswhit/pyproj/archive/v{{ version }}rel.tar.gz
  sha256: 0e19f02ebbf4c253813142ffe06e12489f3861877c3fab75b6c769c1a1960cac

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - ocefpaf
