{% set version = "3.5.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 9859d1591c1863414d875ae0759e72c2cffc01ab989dc64137fbac572cc81bf6

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - pyproj=pyproj.__main__:main
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    # make sure we've fixed the issue in https://github.com/conda-forge/pyproj-feedstock/issues/126
    - export "PROJ_NETWORK=ON"           # [unix]
    - export "PYPROJ_GLOBAL_CONTEXT=ON"  # [unix]
    - set "PROJ_NETWORK=ON"              # [win]
    - set "PYPROJ_GLOBAL_CONTEXT=ON"     # [win]
    - pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_proj
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
