{% set version = "2.3.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 92b8cf0703c25f4e197ec8696b1be567ebb33cb8ba542956142a61df6bf1b766

build:
  number: 1
  skip: True  # [py<35]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj

test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2 
    - jorisvandenbossche
