{% set version = "3.4.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 261eb29b1d55b1eb7f336127344d9b31284d950a9446d1e0d1c2411f7dd8e3ac
  patches:
    # remove on next release, see https://github.com/pyproj4/pyproj/pull/1210
    - 0001-fix-expected-transform-grid-list.patch

build:
  number: 1
  skip: true  # [py<38]
  entry_points:
    - pyproj=pyproj.__main__:main
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    # make sure we've fixed the issue in https://github.com/conda-forge/pyproj-feedstock/issues/126
    - export "PROJ_NETWORK=ON"  # [unix]
    - set "PROJ_NETWORK=ON"     # [win]
    - pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_proj4
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
