{% set version = "3.2.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 48df0d5ab085bd2dc6db3bca79e20bf15b08ffca4f4e42df6d87b566633b800c

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    - export "PROJ_VERSION={{ proj }}"  # [unix]
    - set "PROJ_VERSION={{ proj }}"     # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
