{% set version = "1.9.5.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://github.com/jswhit/pyproj/archive/v{{ version }}rel.tar.gz
  sha256: 0e19f02ebbf4c253813142ffe06e12489f3861877c3fab75b6c769c1a1960cac

build:
  number: 2
  script:
    - del _proj.c  # [win]
    - set "PROJ_DIR=%PREFIX%"  # [win]
    - set "PROJ_LIBDIR=%LIBRARY_LIB%"  # [win]
    - set "PROJ_INCDIR=%LIBRARY_INC%"  # [win]
    - rm -d _proj.c  # [not win]
    - export PROJ_DIR="${PREFIX}"  # [not win]
    - cythonize -a -i _proj.pyx
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj4
  run:
    - python
    - numpy

test:
  imports:
    - pyproj

about:
  home: https://github.com/jswhit/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ.4 library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
