{% set version = "3.3.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
#  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  url: https://github.com/pyproj4/pyproj/archive/refs/tags/3.3rc0.tar.gz
  sha256: 8dd57195cefeeaa4a05d3347a823be27644f0c5d43b7f14c68b7af0646834031

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    - export "PROJ_VERSION={{ proj }}"  # [unix]
    - set "PROJ_VERSION={{ proj }}"     # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely  # [not osx or py<=39]
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
