{% set version = "3.6.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 44aa7c704c2b7d8fb3d483bbf75af6cb2350d30a63b144279a09b75fead501bf

build:
  number: 3
  # we will figure out the ppc64le failures in a subsequent PR
  skip: true  # [py<39 or python_impl == 'pypy']
  entry_points:
    - pyproj=pyproj.__main__:main
  script_env:
    - PROJ_VERSION={{ proj }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - numpy
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - export "PROJ_NETWORK=ON"           # [unix]
    - export "PYPROJ_GLOBAL_CONTEXT=ON"  # [unix]
    - set "PROJ_NETWORK=ON"              # [win]
    - set "PYPROJ_GLOBAL_CONTEXT=ON"     # [win]
    - python -m pytest -v -s
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_proj
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
    - zklaus
