{% set version = "2.4.0" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 8124fe43d81a7caca43df6930110e2bfd2bd3b82b86587eefd6f6d86a81a658e

build:
  number: 0
  skip: True  # [py<35]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely
    - mock
    - numpy
  imports:
    - pyproj
  commands:
    - pytest -v -s

about:
  home: https://github.com/pyproj4/pyproj
  license: OSI
  license_file: LICENSE
  summary: 'Python interface to PROJ library'

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2 
    - jorisvandenbossche
