{% set version = "3.2.1" %}

package:
  name: pyproj
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproj/pyproj-{{ version }}.tar.gz
  sha256: 4a936093825ff55b24c1fc6cc093541fcf6d0f6d406589ed699e62048ebf3877
  patches:
    - 0001-patch-tests-for-proj820.patch

build:
  number: 5
  skip: true  # [py<37]
  entry_points:
    - pyproj=pyproj.__main__:main
  script:
    - export "PROJ_VERSION={{ proj }}"  # [unix]
    - set "PROJ_VERSION={{ proj }}"     # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - proj
  run:
    - python
    - proj
    - certifi

test:
  source_files:
    - test
  requires:
    - pytest
    - shapely  # [not osx or py<=39]
    - numpy
    - pandas
    - xarray
  imports:
    - pyproj
  commands:
    - pyproj --verbose
    - pytest -v -s -k "not test_crs_multiprocess"
about:
  home: https://github.com/pyproj4/pyproj
  license: MIT
  license_file: LICENSE
  summary: Python interface to PROJ library

extra:
  recipe-maintainers:
    - mingwandroid
    - ocefpaf
    - snowman2
    - jorisvandenbossche
    - xylar
