appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bbeXDdwiOV4VoHxTtnYux/7RIYLvtot3xWC5uE+u8jG0Fm15c+6MSxnca6uRMXVBy+KZGkXpApGFeTWbe7Yq2NRHUywOTGHr2kYKNyLhlIGyOcXeso7eUk/IP6VPchfnMDYN7KXzdsFrPgoESQ2mck1oTYRETM1nEKHZzRENchekS2uVV+mvwU6vukGl41coIeOqi/HKz0AdcoSX/we9GApalujPyzs+tr4T9pxI+V2rkHV8jJd3jCBnqqkgpP1HuOXM9KenJ4Ko6tp/obzefgiKTBMY2/Z97eqcrR9JqHojTW3ywZirvKWYycWVtxbU4fDHdU2h8pio7fXMj7F0QY3ZJ7kQ0RVpdOF+edTKunHG/1koWkEO/cgrJelW0kalP7gH8KB9iXWwzm8RX5fzy/I5v9+AfJIvBaBQjfu/YKRNeF3s8tCGaIQnhxm0gmTxYAYXTSOyxMEVAMvRsiVkVJbgNToJ9vWfaeDb9thjhgHox4BTzSVjEt6c23L4Ye1Dt8Qo/jH6CTxFGXx7kXU8iELfCMOe8wVoODBrxe0FFawt4WoxfN+uR9gk3i7BCxjU8ovkC9kQHDl/LQ++hEyablAL5leIoSr41ns0TN/F4TAvCZw09/EnynTsvptcKdIP1YmYhPhUoiblsUNsTWMjdqXm+7BoF1WAF2FL2WzJtgM=}
provider:
  win: azure
